### ISSUE TITLE
Getting the test name

### ISSUE THREAD

**Issue by ysimonson** [reem/stainless#68]
I have a sandbox with a setup method that inserts sample data into a database. Because the tests may run concurrently, I want to isolate the sample data used for one test from another. To do so, I use the test name as part of the key for any data inserted into the database. As a result, I need to pass the test name into `sandbox.setup()` and consequently put the test name in twice, like so:

```rust
describe! foo {
  before_each {
    let mut sandbox = TestSandbox::new();
  }

  after_each {
    sandbox.teardown();
  }

  it "should allow you to do foo" {
    sandbox.setup("should allow you to do foo");
    do_foo(&mut sandbox)
  }
}
```

Is there a cleaner way to do this, i.e. a macro or something I could use such that I don't need to pass the test name into `sandbox.setup()`?

**Comment by ujh** [comment]
Unfortunately there's no way to do this in stainless. I also tried using the `line!()` and `file!()` macros but they don't help here. In fact they're completely broken in stainless right now.

What I would do personally is to have some internal counter in the `TestSandbox` struct that gets incremented atomically so that you get a unique ID each time. Actually maybe using the [uuid](https://crates.io/crates/uuid) crate would be even simpler.

**Comment by ysimonson** [comment]
Makes sense. Thanks for the reply!
